/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uoxx3.cjfx;

import org.gradle.testkit.runner.BuildResult;
import org.gradle.testkit.runner.GradleRunner;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * A simple functional test for the 'uoxx3.cjfx.greeting' plugin.
 */
class CjfxPluginPluginFunctionalTest {
	
	@TempDir
	File projectDir;
	
	private File getBuildFile() {
		return new File(projectDir, "build.gradle");
	}
	
	private File getSettingsFile() {
		return new File(projectDir, "settings.gradle");
	}
	
	@Test
	void canRunTask() throws IOException {
		writeString(getSettingsFile(), "");
		writeString(getBuildFile(),
					"plugins {" +
					"  id('uoxx3.cjfx')" +
					"}");
		
		// Run the build
		GradleRunner runner = GradleRunner.create();
		runner.forwardOutput();
		runner.withPluginClasspath();
		runner.withArguments("greeting");
		runner.withProjectDir(projectDir);
		BuildResult result = runner.build();
		
		// Verify the result
		assertTrue(result.getOutput().contains("Hello from plugin 'uoxx3.cjfx.greeting'"));
	}
	
	private void writeString(File file, String string) throws IOException {
		try (Writer writer = new FileWriter(file)) {
			writer.write(string);
		}
	}
	
}
