/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uoxx3.cjfx;

import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * A simple unit test for the 'uoxx3.cjfx.greeting' plugin.
 */
class CjfxPluginEntryTest {
	
	@Test
	void pluginRegistersATask() {
		// Create a test project and apply the plugin
		Project project = ProjectBuilder.builder().build();
		project.getPlugins().apply("uoxx3.cjfx.greeting");
		
		// Verify the result
		assertNotNull(project.getTasks().findByName("greeting"));
	}
	
}
